version: "2.3"
services:
  mavinxStoreDB:
    container_name: MavinxStoreDatabase
    image: postgres:10-alpine
    restart: always
    env_file:
      - db.env
    volumes:
    - ./mavinx_db:/var/lib/postgresql/data

  proj:
    container_name: mavinxStoreProject
    build:
      context: ./Mavinx
    command: python3 manage.py runserver 0.0.0.0:8000 --setting=mavinx.settings.production
    restart: always
    volumes:
      - ./Mavinx:/code
      - static:/code/mavinx/staticfiles
      - locale:/code/mavinx/locale
    ports:
      - '8080:8000'
    depends_on:
      - mavinxStoreDB
      - django_commands
    env_file:
      - .env

  django_commands:
    build: ./Mavinx
    command: bash -c "django-admin compilemessages &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      /bin/bash load_head_fixtures.sh"
    volumes:
      - static:/code/mavinx/staticfiles
      - locale:/code/mavinx/locale
    depends_on:
      - mavinxStoreDB
    env_file:
      - .env

volumes:
  static:
  locale: