version: "2.3"
services:
  mavinxStoreDB:
    container_name: MavinxStoreDatabase
    image: postgres:10-alpine
    restart: always
    env_file:
      - db.env
    volumes:
    - ./mavinx_db:/var/lib/postgresql/data
  proj:
    container_name: mavinxStoreProject
    build: ./Mavinx/
    command: python3 manage.py runserver --setting=mavinx.settings.local 0.0.0.0:8000
    restart: always
    ports:
    - '8080:8000'
    depends_on:
      - mavinxStoreDB
    env_file:
      - .env