# Generated by Django 3.0.7 on 2020-07-22 10:00

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='head_video',
            field=models.FileField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_video_project'),
        ),
    ]
