# Generated by Django 3.0.7 on 2020-07-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_audience',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_idea',
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='project_audience',
            field=models.CharField(max_length=100, null=True, verbose_name='vnm_project_audience'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='project_idea',
            field=models.CharField(max_length=100, null=True, verbose_name='vnm_project_idea'),
        ),
    ]
