# Generated by Django 3.0.7 on 2020-07-08 14:14

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_publish',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='vnm_date_blog'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='area',
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.ManyToManyField(related_name='project', to='head.Area', verbose_name='vnm_area_project'),
        ),
    ]
