# Generated by Django 3.0.8 on 2020-07-29 06:48

from django.db import migrations, models
import django.db.models.deletion
import head.utils
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=head.utils.custom_upload_to, verbose_name='vn_blog_writ_image')),
            ],
            options={
                'verbose_name': 'vn_blog_writ',
                'verbose_name_plural': 'vnp_blog_writ',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='blog',
            name='writers',
            field=models.ManyToManyField(related_name='blogs', to='head.BlogWriter', verbose_name='vnm_writ_blog'),
        ),
        migrations.CreateModel(
            name='BlogWriterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='vnm_name_blog_writ')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='head.BlogWriter')),
            ],
            options={
                'verbose_name': 'vn_blog_writ Translation',
                'db_table': 'head_blogwriter_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
