# Generated by Django 3.0.8 on 2020-08-04 09:18

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='one_project_image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_company_one_project_image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_android_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='vnm_android_link_project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_ios_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='vnm_ios_link_project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_web_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='vnm_web_link_project'),
        ),
    ]
