# Generated by Django 3.0.7 on 2020-07-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sector',
            new_name='sectors',
        ),
        migrations.AlterModelTable(
            name='projectsector',
            table='head_project_sector',
        ),
        migrations.AlterModelTable(
            name='projectsectortranslation',
            table='head_project_sector_translation',
        ),
        migrations.AlterModelTable(
            name='technologyusing',
            table='head_project_tech_using',
        ),
    ]
