# Generated by Django 3.0.7 on 2020-07-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20200720_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'vnm_name_technology', 'verbose_name_plural': 'vnm_name_technology'},
        ),
        migrations.CreateModel(
            name='TechnologyUsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='vnm_name_technology_using')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.Technology', verbose_name='vnm_name_technology_using_parent')),
            ],
            options={
                'verbose_name': 'vnm_name_technology_use',
                'verbose_name_plural': 'vnm_name_technology_use',
            },
        ),
    ]
