# Generated by Django 3.0.8 on 2020-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20200804_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcaseimagestranslation',
            name='description',
            field=models.TextField(verbose_name='vnm_blog_case_desc'),
        ),
    ]
