# Generated by Django 3.0.7 on 2020-07-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_order_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='vnm_phone_name'),
        ),
    ]
