# Generated by Django 3.0.8 on 2020-07-27 12:28

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20200723_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_image'),
        ),
        migrations.DeleteModel(
            name='AboutImage',
        ),
    ]
