# Generated by Django 3.0.7 on 2020-07-09 05:22

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20200708_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_publish',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, null=True, verbose_name='vnm_date_blog'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='area',
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.ManyToManyField(to='head.Area', verbose_name='vnm_name_area'),
        ),
    ]
