# Generated by Django 3.0.7 on 2020-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20200721_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(related_name='projects', to='head.TechnologyUsing', verbose_name='vnm_technology_project'),
        ),
    ]
