# Generated by Django 3.0.8 on 2020-07-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20200727_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttranslation',
            name='name',
        ),
    ]
