# Generated by Django 3.0.7 on 2020-07-03 05:43

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='vnm_company_name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_file_order'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='name',
            field=models.CharField(max_length=30, verbose_name='vnm_name_project'),
        ),
    ]
