# Generated by Django 3.0.8 on 2020-09-09 11:40

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20200828_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='head_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='head_project_image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_image_blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='one_project_image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_image_blog'),
        ),
    ]
