# Generated by Django 3.0.7 on 2020-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20200709_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.ManyToManyField(related_name='areas', to='head.Area', verbose_name='vnm_name_area'),
        ),
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.ManyToManyField(related_name='projects', to='head.Area', verbose_name='vnm_area_project'),
        ),
    ]
