# Generated by Django 3.0.7 on 2020-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20200722_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_audience',
            field=models.CharField(max_length=100, null=True, verbose_name='vnm_project_audience'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_idea',
            field=models.CharField(max_length=100, null=True, verbose_name='vnm_project_idea'),
        ),
    ]
