# Generated by Django 3.0.7 on 2020-07-22 12:56

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_auto_20200722_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChallenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='head.ProjectChallenges', verbose_name='vnm_project_chel_name'),
        ),
        migrations.CreateModel(
            name='ProjectChallengesTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(null=True, verbose_name='vnm_project_chel_desc')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='head.ProjectChallenges')),
            ],
            options={
                'verbose_name': 'project challenges Translation',
                'db_table': 'head_projectchallenges_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
