# Generated by Django 3.0.7 on 2020-07-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_auto_20200721_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technology',
            new_name='technology_use',
        ),
    ]
