# Generated by Django 3.0.8 on 2020-09-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_auto_20200909_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='head_project_image',
            new_name='head_blog_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='one_project_image',
            new_name='one_blog_image',
        ),
    ]
