# Generated by Django 3.0.7 on 2020-07-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_auto_20200703_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='vnm_subc_email')),
            ],
            options={
                'verbose_name': 'vm_subscribe',
                'verbose_name_plural': 'vmp_subscribe',
            },
        ),
    ]
