# Generated by Django 3.0.7 on 2020-07-21 12:25

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_auto_20200721_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_image_blog'),
        ),
    ]
