# Generated by Django 3.0.7 on 2020-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='completed_project',
            field=models.IntegerField(null=True, verbose_name='vnm_completed_project'),
        ),
    ]
