# Generated by Django 3.0.7 on 2020-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_auto_20200722_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchallenges',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='vnm_project_chel_name_mark'),
        ),
    ]
