# Generated by Django 3.0.7 on 2020-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_auto_20200709_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtranslation',
            name='name',
            field=models.TextField(max_length=255, verbose_name='vnm_name_review'),
        ),
    ]
