# Generated by Django 3.0.7 on 2020-07-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_contact_completed_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='vnm_name_area'),
        ),
    ]
