# Generated by Django 3.0.8 on 2020-09-09 11:48

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_auto_20200909_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='head_blog_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='one_blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_image_blog_one'),
        ),
    ]
