# Generated by Django 3.0.7 on 2020-07-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_auto_20200709_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='android_count_proj',
            field=models.IntegerField(null=True, verbose_name='vnm_completed_project_and'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ios_count_proj',
            field=models.IntegerField(null=True, verbose_name='vnm_completed_project_ios'),
        ),
        migrations.AddField(
            model_name='contact',
            name='test_count_proj',
            field=models.IntegerField(null=True, verbose_name='vnm_completed_project_test'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ux_ui_count_proj',
            field=models.IntegerField(null=True, verbose_name='vnm_completed_project_ux_ui'),
        ),
        migrations.AddField(
            model_name='contact',
            name='web_count_proj',
            field=models.IntegerField(null=True, verbose_name='vnm_completed_project_web'),
        ),
    ]
