# Generated by Django 3.0.7 on 2020-07-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_projectchallenges_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='projectchallenges',
            name='name',
        ),
        migrations.AddField(
            model_name='projectchallenges',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_challenges', to='head.Project', verbose_name='vnm_project_chel'),
        ),
    ]
