# Generated by Django 3.0.7 on 2020-07-21 12:31

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_technology_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyusing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_image_tech_child'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_image_tech'),
        ),
    ]
