# Generated by Django 3.0.7 on 2020-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_auto_20200722_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectchallenges',
            options={'verbose_name': 'vn_project_challenge', 'verbose_name_plural': 'vnp_project_challenge'},
        ),
        migrations.AlterModelOptions(
            name='projectchallengestranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'vn_project_challenge Translation'},
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='result',
            field=models.TextField(null=True, verbose_name='vnm_location_project'),
        ),
        migrations.AlterModelTable(
            name='projectchallenges',
            table='head_project_challenge',
        ),
        migrations.AlterModelTable(
            name='projectchallengestranslation',
            table='head_project_challenge_translation',
        ),
    ]
