# Generated by Django 3.0.7 on 2020-07-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_auto_20200706_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
    ]
