# Generated by Django 3.0.8 on 2020-10-05 09:28

from django.db import migrations
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_auto_20200909_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='head_image',
        ),
        migrations.AlterField(
            model_name='blogtranslation',
            name='name',
            field=quilljs.fields.RichTextField(max_length=100, unique=True, verbose_name='vnm_name_blog'),
        ),
    ]
