# Generated by Django 3.0.7 on 2020-07-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_auto_20200721_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='image',
        ),
        migrations.RemoveField(
            model_name='technologyusing',
            name='image',
        ),
    ]
