# Generated by Django 3.0.7 on 2020-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0008_auto_20200707_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=1, verbose_name='vnm_date_views'),
        ),
    ]
