# Generated by Django 3.0.7 on 2020-07-22 13:38

from django.db import migrations, models
import django.db.models.deletion
import head.models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0008_auto_20200722_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImage',
            new_name='ProjectNumberImages',
        ),
        migrations.RenameModel(
            old_name='ProjectImageTranslation',
            new_name='ProjectNumberImagesTranslation',
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='result',
            field=models.TextField(null=True, verbose_name='vnm_result_project'),
        ),
        migrations.AlterModelTable(
            name='projectnumberimages',
            table='head_project_number_images',
        ),
        migrations.AlterModelTable(
            name='projectnumberimagestranslation',
            table='head_project_number_images_translation',
        ),
        migrations.CreateModel(
            name='ProjectSliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=head.models.custom_upload_to_project_image, verbose_name='vnm_projectimage_slider')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_slider_images', to='head.Project', verbose_name='vnm_projectimageslider_project')),
            ],
            options={
                'verbose_name': 'vn_project_slider_images',
                'verbose_name_plural': 'vnp_project_slider_images',
                'db_table': 'head_project_slider_images',
            },
        ),
    ]
