# Generated by Django 3.0.8 on 2020-10-05 09:36

from django.db import migrations
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0009_auto_20201005_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcaseimagestranslation',
            name='description',
            field=quilljs.fields.RichTextField(verbose_name='vnm_blog_case_desc'),
        ),
    ]
