# Generated by Django 3.0.8 on 2020-10-05 09:43

from django.db import migrations, models
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0010_auto_20201005_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtranslation',
            name='description',
        ),
        migrations.AlterField(
            model_name='blogcaseimagestranslation',
            name='description',
            field=quilljs.fields.RichTextField(null=True, verbose_name='vnm_blog_case_desc'),
        ),
        migrations.AlterField(
            model_name='blogcaseimagestranslation',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='vnm_blog_case_name'),
        ),
    ]
