# Generated by Django 3.0.8 on 2020-10-05 10:00

from django.db import migrations, models
import head.utils


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0011_auto_20201005_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcaseimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=head.utils.custom_upload_to, verbose_name='vnm_case_images'),
        ),
        migrations.AlterField(
            model_name='blogcaseimagestranslation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='vnm_blog_case_name'),
        ),
    ]
